import tools.*;
import java.math.BigDecimal;
import java.util.List;
import java.util.ArrayList;

class q026 {
	public static void main(String[] args){
		int[] primes = Prime.getPrimes(1000);
		List<Integer> cyclicPrimes = new ArrayList<Integer>();

		int curPrime = 0;
		String curCyclic = "";
		for (int p : primes){
			if (10 % p != 0){
				// Finds largest cyclic number generated by the given primes
				// https://en.wikipedia.org/wiki/Cyclic_number
				int base = 10;
				int prime = 17;
				int t=0, r=1, n=0;
				String str = "";
				do {
					++t;
					int x = r * base;
					int d = x/p;
					r = x % p;
					str += String.valueOf(d);
				} while (r != 1);

				if (str.length() > curCyclic.length()){
					curCyclic = str;
					curPrime = p;
				}
			}
		}
		System.out.println(curPrime);
	}
}